-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/GlobalBlocking/sql/abstractschemachanges/patch-globalblocks-timestamps.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  globalblocks ALTER gb_timestamp TYPE TIMESTAMPTZ;
ALTER TABLE  globalblocks ALTER gb_timestamp
DROP  DEFAULT;
ALTER TABLE  globalblocks ALTER gb_timestamp TYPE TIMESTAMPTZ;
ALTER TABLE  globalblocks ALTER gb_expiry TYPE TIMESTAMPTZ;
ALTER TABLE  globalblocks ALTER gb_expiry
DROP  DEFAULT;
ALTER TABLE  globalblocks ALTER gb_expiry TYPE TIMESTAMPTZ;