-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/GlobalBlocking/sql/abstractSchemaChanges/patch-globalblocks-gb_anon_only.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  globalblocks ALTER gb_anon_only TYPE SMALLINT;
ALTER TABLE  globalblocks ALTER gb_anon_only
SET  DEFAULT 0;