-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/GlobalBlocking/sql/tables-globalblocks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE globalblocks (
  gb_id SERIAL NOT NULL,
  gb_address VARCHAR(255) NOT NULL,
  gb_target_central_id INT DEFAULT 0 NOT NULL,
  gb_by VARCHAR(255) DEFAULT '' NOT NULL,
  gb_by_central_id INT NOT NULL,
  gb_by_wiki TEXT NOT NULL,
  gb_reason TEXT NOT NULL,
  gb_timestamp TIMESTAMPTZ NOT NULL,
  gb_anon_only SMALLINT DEFAULT 0 NOT NULL,
  gb_expiry TIMESTAMPTZ NOT NULL,
  gb_range_start TEXT NOT NULL,
  gb_range_end TEXT NOT NULL,
  PRIMARY KEY(gb_id)
);

CREATE UNIQUE INDEX gb_address ON globalblocks (gb_address, gb_anon_only);

CREATE INDEX gb_target_central_id ON globalblocks (gb_target_central_id);

CREATE INDEX gb_range ON globalblocks (gb_range_start, gb_range_end);

CREATE INDEX gb_timestamp ON globalblocks (gb_timestamp);

CREATE INDEX gb_expiry ON globalblocks (gb_expiry);
