-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/GlobalBlocking/sql/tables-global_block_whitelist.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE global_block_whitelist (
  gbw_id INT NOT NULL,
  gbw_address TEXT DEFAULT '' NOT NULL,
  gbw_target_central_id INT DEFAULT 0 NOT NULL,
  gbw_by INT NOT NULL,
  gbw_by_text TEXT NOT NULL,
  gbw_reason TEXT NOT NULL,
  gbw_expiry TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(gbw_id)
);

CREATE INDEX gbw_by ON global_block_whitelist (gbw_by);
