-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/GlobalBlocking/sql/abstractSchemaChanges/patch-global_block_whitelist-default-gbw_address.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__global_block_whitelist AS
SELECT
  gbw_id,
  gbw_address,
  gbw_target_central_id,
  gbw_by,
  gbw_by_text,
  gbw_reason,
  gbw_expiry
FROM /*_*/global_block_whitelist;
DROP TABLE /*_*/global_block_whitelist;


CREATE TABLE /*_*/global_block_whitelist (
    gbw_id INTEGER NOT NULL,
    gbw_address BLOB DEFAULT '' NOT NULL,
    gbw_target_central_id INTEGER UNSIGNED DEFAULT 0 NOT NULL,
    gbw_by INTEGER NOT NULL,
    gbw_by_text BLOB NOT NULL,
    gbw_reason BLOB NOT NULL,
    gbw_expiry BLOB NOT NULL,
    PRIMARY KEY(gbw_id)
  );
INSERT INTO /*_*/global_block_whitelist (
    gbw_id, gbw_address, gbw_target_central_id,
    gbw_by, gbw_by_text, gbw_reason,
    gbw_expiry
  )
SELECT
  gbw_id,
  gbw_address,
  gbw_target_central_id,
  gbw_by,
  gbw_by_text,
  gbw_reason,
  gbw_expiry
FROM
  /*_*/__temp__global_block_whitelist;
DROP TABLE /*_*/__temp__global_block_whitelist;

CREATE INDEX gbw_by ON /*_*/global_block_whitelist (gbw_by);
