-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/GlobalBlocking/sql/tables-global_block_whitelist.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/global_block_whitelist (
  gbw_id INTEGER NOT NULL,
  gbw_address BLOB DEFAULT '' NOT NULL,
  gbw_target_central_id INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  gbw_by INTEGER NOT NULL,
  gbw_by_text BLOB NOT NULL,
  gbw_reason BLOB NOT NULL,
  gbw_expiry BLOB NOT NULL,
  PRIMARY KEY(gbw_id)
);

CREATE INDEX gbw_by ON /*_*/global_block_whitelist (gbw_by);
