-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/GlobalBlocking/sql/abstractSchemaChanges/patch-globalblocks-modify-gb_autoblock_parent_id-default.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/globalblocks
  CHANGE gb_autoblock_parent_id gb_autoblock_parent_id INT UNSIGNED DEFAULT 0 NOT NULL;
