-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/GlobalBlocking/sql/abstractSchemaChanges/patch-add-gb_target_central_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/globalblocks
  ADD gb_target_central_id INT UNSIGNED DEFAULT 0 NOT NULL;

CREATE INDEX gb_target_central_id ON /*_*/globalblocks (gb_target_central_id);
