-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-globalblocks-modify-gb_id-unsigned.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/globalblocks
  CHANGE gb_id gb_id INT UNSIGNED AUTO_INCREMENT NOT NULL;
