-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/GlobalBlocking/sql/abstractSchemaChanges/patch-globalblocks-gb_anon_only.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/globalblocks
CHANGE  gb_anon_only gb_anon_only TINYINT(1) DEFAULT 0 NOT NULL;