-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-global_block_whitelist-modify-gbw_id-unsigned.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/global_block_whitelist
  CHANGE gbw_id gbw_id INT UNSIGNED NOT NULL;
