-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/GlobalBlocking/sql/abstractSchemaChanges/patch-globalblocks-add-gb_enable_autoblock.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/globalblocks
  ADD gb_enable_autoblock TINYINT(1) DEFAULT 0 NOT NULL;
