-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-globalblocks-modify-gb_address-type.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/globalblocks
  CHANGE gb_address gb_address VARBINARY(255) NOT NULL;
