-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/GlobalBlocking/sql/abstractSchemaChanges/patch-global_block_whitelist-gbw_expiry-type.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/global_block_whitelist
  CHANGE gbw_expiry gbw_expiry VARBINARY(14) NOT NULL;
