-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/GlobalBlocking/sql/tables-global_block_whitelist.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/global_block_whitelist (
  gbw_id INT NOT NULL,
  gbw_address VARBINARY(255) DEFAULT '' NOT NULL,
  gbw_target_central_id INT UNSIGNED DEFAULT 0 NOT NULL,
  gbw_by INT NOT NULL,
  gbw_by_text VARBINARY(255) NOT NULL,
  gbw_reason VARBINARY(767) NOT NULL,
  gbw_expiry VARBINARY(14) NOT NULL,
  INDEX gbw_by (gbw_by),
  PRIMARY KEY(gbw_id)
) /*$wgDBTableOptions*/;
