-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/GlobalBlocking/sql/tables-globalblocks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/globalblocks (
  gb_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  gb_address VARCHAR(255) NOT NULL,
  gb_target_central_id INT UNSIGNED DEFAULT 0 NOT NULL,
  gb_by_central_id INT UNSIGNED NOT NULL,
  gb_by_wiki VARBINARY(255) NOT NULL,
  gb_reason VARBINARY(767) NOT NULL,
  gb_timestamp BINARY(14) NOT NULL,
  gb_anon_only TINYINT(1) DEFAULT 0 NOT NULL,
  gb_create_account TINYINT(1) DEFAULT 1 NOT NULL,
  gb_enable_autoblock TINYINT(1) DEFAULT 0 NOT NULL,
  gb_autoblock_parent_id INT UNSIGNED DEFAULT 0 NOT NULL,
  gb_expiry VARBINARY(14) NOT NULL,
  gb_range_start VARBINARY(35) NOT NULL,
  gb_range_end VARBINARY(35) NOT NULL,
  UNIQUE INDEX gb_address_autoblock_parent_id (
    gb_address, gb_autoblock_parent_id
  ),
  INDEX gb_target_central_id (gb_target_central_id),
  INDEX gb_range (gb_range_start, gb_range_end),
  INDEX gb_timestamp (gb_timestamp),
  INDEX gb_expiry (gb_expiry),
  INDEX gb_autoblock_parent_id (gb_autoblock_parent_id),
  PRIMARY KEY(gb_id)
) /*$wgDBTableOptions*/;
